---
# Usage: http://ruhoh.com

RuhohSpec: "2.1"

production_url: "http://lisawalley.com"

base_path: "/"

iamdev :
  use : "theme"

_root:
  summary_lines: 20
  rss:
    enable: false
  paginator:
    enable: false

posts:
  sort: ["date", "desc"]
  permalink: "/:categories/:title/"
  summary_lines: 20
  latest: 5
  rss:
    enable: true
    limit: 5
  paginator:
    enable: false
    url: "/posts/index/"
    per_page: 5
    root_page: '/'

asset_pipeline:
  enable: false

widgets :

  analytics :
    use : google
    # -- config for google --
    tracking_id : 'UA-39172112-1'
    # -- config for getclicky  --
    # site_id :

  comments :
    use : disqus
    enable : false
    # -- config for disqus --
    short_name : ???

    # -- config for livefyre --
    # site_id : 123

    # -- config for intensedebate --
    # account : 123abc

    # -- config for facebook --
    # appid : 123
    # num_posts: 5
    # width: 580
    # colorscheme: light

  google_prettify :
    linenums : true
